import type { Metadata, Viewport } from "next";
import "./_scss/globals.scss";

import localFont from "next/font/local";
import Providers from "./_context/Providers";
import { useEffect } from "react";
import LocalStorage from "./_utils/LocalStorage";
import { auth } from "./_http/API/userApi";
import { useTypesSelector } from "./_hooks/useTypesSelector";
import { useTypesDispatch } from "./_hooks/useTypesDispatch";
import { userSlice } from "./_store/reducers/userSlice";
import { contentSlice } from "./_store/reducers/contentSlice";
import ClientRootLayout from "./_components/ClientRootLayout/ClientRootLayout";
import LoadingScreen from "./_components/LoadingScreen/LoadingScreen";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";
import Head from "next/head";

const gilroy = localFont({
    src: [
        {
            path: "../public/fonts/Gilroy-Medium.ttf",
            weight: "500",
            style: "medium",
        },
        {
            path: "../public/fonts/Gilroy-Medium.woff",
            weight: "500",
            style: "medium",
        },
        {
            path: "../public/fonts/Gilroy-Light.ttf",
            weight: "300",
            style: "light",
        },
        {
            path: "../public/fonts/Gilroy-Light.woff",
            weight: "300",
            style: "light",
        },
    ],
    display: "swap",
    variable: "--font",
});

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    // maximumScale: 1,
    // userScalable: false,
};

export const metadata: Metadata = {
    title: "DESC Education",
    description: "Generated by create next app",
    icons: {
        icon: [
            {
                url: "/favicons/favicon.ico",
                type: "image/x-icon",
                rel: "icon",
            },
            {
                url: "/favicons/apple-touch-icon.png",
                type: "image/png",
                rel: "apple-touch-icon",
            },
            {
                url: "/favicons/favicon-32x32.png",
                type: "image/png",
                rel: "icon",
                sizes: "32x32",
            },
            {
                url: "/favicons/favicon-16x16.png",
                type: "image/png",
                rel: "icon",
                sizes: "16x16",
            },
        ],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={gilroy.className}>
                <Providers>
                    <ClientRootLayout>
                        <>
                            <Header />
                            <LoadingScreen />
                            {children}
                            <Footer />
                        </>
                    </ClientRootLayout>
                </Providers>
            </body>
        </html>
    );
}
