import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./scss/globals.scss";

import localFont from "next/font/local";
import Providers from "./context/Providers";

const gilroy = localFont({
    src: [
        {
            path: "../public/fonts/Gilroy-Medium.ttf",
            weight: "500",
            style: "medium",
        },
        {
            path: "../public/fonts/Gilroy-Medium.woff",
            weight: "500",
            style: "medium",
        },
        {
            path: "../public/fonts/Gilroy-Light.ttf",
            weight: "300",
            style: "light",
        },
        {
            path: "../public/fonts/Gilroy-Light.woff",
            weight: "300",
            style: "light",
        },
    ],
    display: "swap",
    variable: "--font",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={gilroy.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
