import type { Metadata } from "next";
import "./_scss/globals.scss";

import localFont from "next/font/local";
import Providers from "./_context/Providers";
import { useEffect } from "react";
import LocalStorage from "./_utils/LocalStorage";
import { auth } from "./_http/API/userApi";
import { useTypesSelector } from "./_hooks/useTypesSelector";
import { useTypesDispatch } from "./_hooks/useTypesDispatch";
import { userSlice } from "./_store/reducers/userSlice";
import { contentSlice } from "./_store/reducers/contentSlice";
import ClientRootLayout from "./_components/ClientRootLayout/ClientRootLayout";
import LoadingScreen from "./_components/LoadingScreen/LoadingScreen";

const gilroy = localFont({
    src: [
        {
            path: "../public/fonts/Gilroy-Medium.ttf",
            weight: "500",
            style: "medium",
        },
        {
            path: "../public/fonts/Gilroy-Medium.woff",
            weight: "500",
            style: "medium",
        },
        {
            path: "../public/fonts/Gilroy-Light.ttf",
            weight: "300",
            style: "light",
        },
        {
            path: "../public/fonts/Gilroy-Light.woff",
            weight: "300",
            style: "light",
        },
    ],
    display: "swap",
    variable: "--font",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={gilroy.className}>
                <Providers>
                    <ClientRootLayout>
                        <>
                            <LoadingScreen />
                            {children}
                        </>
                    </ClientRootLayout>
                </Providers>
            </body>
        </html>
    );
}
